name: C/C++ CI

on:
  push:
    branches: [ master, v2, feature/tests ]
  pull_request:
    branches: [ master, v2, feature/tests ]

jobs:
  
  linux-test:
    name: Linux test
    runs-on: ubuntu-latest
    env: 
      INPUT_DIR: ./test/virus
 
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
      
    - name: build + all2all (default k)
      run: |
        ./kmer-db build ${INPUT_DIR}/sequences.list k18.db
        ./kmer-db all2all k18.db k18.csv
        cmp k18.csv ${INPUT_DIR}/k18.csv
    
    - name: build + all2all (default k, multifasta)
      run: |
        ./kmer-db build -multisample-fasta ${INPUT_DIR}/multi.list k18.multi.db
        ./kmer-db all2all k18.multi.db k18.multi.csv
        cmp k18.multi.csv ${INPUT_DIR}/k18.csv
        
    - name: build + all2all (default k, 2 x multifasta)
      run: |
        ./kmer-db build -multisample-fasta ${INPUT_DIR}/multi.split.list k18.multi.split.db
        ./kmer-db all2all k18.multi.split.db k18.multi.split.csv
        cmp k18.multi.split.csv ${INPUT_DIR}/k18.csv
        
    - name: build + all2all (default k, extend)
      run: |
        ./kmer-db build ${INPUT_DIR}/sequences.part1 k18.parts.db
        ./kmer-db build -extend -k 25 ${INPUT_DIR}/sequences.part2 k18.parts.db
        ./kmer-db all2all k18.parts.db k18.parts.csv
        cmp k18.parts.csv ${INPUT_DIR}/k18.csv
        
    - name: build + all2all (default k, fraction 0.1)
      run: |    
        ./kmer-db build -f 0.1 ${INPUT_DIR}/sequences.list k18.frac.db
        ./kmer-db all2all k18.frac.db k18.frac.csv
        cmp k18.frac.csv ${INPUT_DIR}/k18.frac.csv

    - name: minhash + build + all2all (default k, fraction 0.1)
      run: |
        ./kmer-db minhash 0.1 ${INPUT_DIR}/sequences.list
        ./kmer-db build -from-minhash -k 25 ${INPUT_DIR}/sequences.list k18.minhash.db
        ./kmer-db all2all k18.minhash.db k18.minhash.csv
        cmp k18.minhash.csv ${INPUT_DIR}/k18.frac.csv
        
        
    - name: build + all2all (k=24)
      run: |
        ./kmer-db build -k 24 ${INPUT_DIR}/sequences.list k24.db
        ./kmer-db all2all k24.db k24.csv
        cmp k24.csv ${INPUT_DIR}/k24.csv

    - name: distance (default k)
      run: | 
        ./kmer-db distance jaccard min max cosine mash k18.csv
        cmp k18.csv.jaccard ${INPUT_DIR}/k18.csv.jaccard
        cmp k18.csv.min ${INPUT_DIR}/k18.csv.min
        cmp k18.csv.max ${INPUT_DIR}/k18.csv.max
        cmp k18.csv.cosine ${INPUT_DIR}/k18.csv.cosine
        cmp k18.csv.mash ${INPUT_DIR}/k18.csv.mash
      
      
  macos-build:
    name: macOS test
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make

